- name: Deploy to GitHub Pages - Python
  # You may pin to the exact commit or the version.
  # uses: evamaxfield/github-pages-deploy-action-python@17d33ff802dccee8cd2c98a5dbd26c3648b4027a
  uses: evamaxfield/github-pages-deploy-action-python@2.1.0
